name: PingSafe Scan

on:
  # Triggers the workflow when pull_request created on master/main branch
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ master, main ]

jobs:
  pingsafe-cli:
    runs-on: ubuntu-latest
    container:
      image: pingsafe/cli:latest
      options: --entrypoint ""

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Configure Pingsafe cli
        run: pingsafe-cli config --api-token $TOKEN
        env:
         TOKEN: ${{secrets.PINGSAFE_TOKEN}}

      - name: Mark present working directory as safe
        run: git config --global --add safe.directory $PWD

      - name: Run Secret Detector
        id: secret-detector
        run:  pingsafe-cli scan secret -d $PWD --pull-request origin/$SRC $DEST --publish-result --repo-full-name $REPO_FULL_NAME  --repo-url $REPO_URL/$REPO_FULL_NAME 
        env:
          DEST: ${{ github.event.pull_request.base.sha }}
          SRC: ${{ github.event.pull_request.head.ref }}
          REPO_FULL_NAME: ${{ github.repository }}
          REPO_URL: ${{ github.server_url }}
